### ISSUE TITLE
Because aw-client (0.3.1 git rev master) depends on click (^7.1.1) which doesn't match any versions, aw-client is forbidden

### ISSUE THREAD

**Issue by ronilaukkarinen** [ActivityWatch/aw-watcher-input#1]
I have a macOS Catalina, poetry and python 3.9 installed.

Error installing:

```
demon aw-watcher-input (master) $ poetry install
Installing dependencies from lock file

  SolverProblemError

  Because aw-client (0.3.1 git rev master) depends on click (^7.1.1) which doesn't match any versions, aw-client is forbidden.
  So, because aw-watcher-input depends on aw-client (0.3.1 git branch master), version solving failed.

  at /usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by ErikBjare** [comment]
That happens sometimes when dependency locks get out of sync. 

Try running `poetry update`. I'll push a fix later today.

**Comment by ErikBjare** [comment]
I've updated version locks across many repos today, so this should no longer be an issue.

**Comment by melgalvez** [comment]
Hi, can you help about this error? Even updated the poetry, still same error with the new version of the repo?

Installing the current project: aw-watcher-afk (0.2.0)
make[1]: Leaving directory `/home/alyaleuser/activitywatch/aw-watcher-afk'
make --directory=aw-watcher-window build
make[1]: Entering directory `/home/alyaleuser/activitywatch/aw-watcher-window'
poetry install
Installing dependencies from lock file

  SolverProblemError

  Because aw-client (0.3.1 git rev master) depends on click (^7.1.1) which doesn't match any versions, aw-client is forbidden.
  So, because aw-watcher-window depends on aw-client (0.3.1 git branch master), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/alyaleuser/activitywatch/aw-watcher-window'
make: *** [build] Error 2
